FROM rocker/tidyverse:latest

# Install R packages
RUN R -e "install.packages(c('dplyr', 'nloptr', 'lme4', 'lubridate', 'readr', 'tidyr', 'renv'), repos='http://cran.rstudio.com/')"

# Copy the renv.lock file and renv directory if they exist
COPY renv.lock renv.lock
COPY renv/ renv/

# Restore the renv environment
RUN R -e "renv::restore()"

